name: Build SuperLauncher

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install PySide6 pyinstaller

      - name: Build Windows EXE
        run: |
          pyinstaller --onefile --windowed --name SuperLauncher main.py

      - name: Upload Windows Build
        uses: actions/upload-artifact@v4
        with:
          name: SuperLauncher-Windows
          path: dist/SuperLauncher.exe

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: |
          python3 -m pip install --upgrade pip
          pip3 install PySide6 pyinstaller

      - name: Build macOS APP
        run: |
          pyinstaller --onefile --windowed --name SuperLauncher main.py

      - name: Upload macOS Build
        uses: actions/upload-artifact@v4
        with:
          name: SuperLauncher-macOS
          path: dist/SuperLauncher
